# Generated by Django 2.1.7 on 2019-03-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='name_equipament',
            new_name='Equipamento',
        ),
        migrations.AlterField(
            model_name='equipaments',
            name='location',
            field=models.TextField(verbose_name='Endereçoo'),
        ),
    ]
