# Generated by Django 2.1.7 on 2019-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipaments', '0004_auto_20190321_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipaments',
            name='location',
        ),
        migrations.AddField(
            model_name='equipaments',
            name='bairro',
            field=models.CharField(default='1', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipaments',
            name='numero',
            field=models.CharField(default='1', max_length=10, verbose_name='Nº'),
            preserve_default=False,
        ),
    ]
