# Generated by Django 2.1.7 on 2019-03-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipaments', '0005_auto_20190322_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipaments',
            name='mac',
            field=models.CharField(default='1', max_length=10, verbose_name='Mac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipaments',
            name='rua',
            field=models.CharField(default='1', max_length=100, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
