# Generated by Django 2.1.7 on 2019-03-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipaments', '0006_auto_20190322_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='location',
        ),
        migrations.AddField(
            model_name='clients',
            name='bairro',
            field=models.CharField(default='1', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='numero',
            field=models.CharField(default='1', max_length=10, verbose_name='Nº'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='rua',
            field=models.CharField(default='1', max_length=100, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
