# Generated by Django 2.1.7 on 2019-03-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipaments', '0008_clients_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='planos',
            field=models.CharField(choices=[('3MB', '3MB'), ('5MB', '5MB'), ('10MB', '10MB'), ('15MB', '15MB'), ('20MB', '20MB'), ('25MB', '25MB'), ('50MB', '50MB')], default='3MB', max_length=5),
            preserve_default=False,
        ),
    ]
